#!/usr/bin/env python3
import argparse
import datetime as dt
import glob
import os
import re
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
ADR_DIR = os.path.join(ROOT, "docs", "adr")
INDEX = os.path.join(ADR_DIR, "INDEX.md")
ADR_PATTERN = "ADR-[0-9][0-9][0-9][0-9]-*.md"


def slugify(s: str) -> str:
    return re.sub(r"-+", "-", re.sub(r"[^a-z0-9]+", "-", s.lower())).strip("-")


def adr_number_from_name(name: str) -> int | None:
    m = re.match(r"ADR-([0-9]{4})-", name)
    if not m:
        return None
    return int(m.group(1))


def iter_adr_files() -> list[str]:
    return sorted(glob.glob(os.path.join(ADR_DIR, ADR_PATTERN)))


def next_id() -> str:
    os.makedirs(ADR_DIR, exist_ok=True)
    ids: list[int] = []
    for p in iter_adr_files():
        n = adr_number_from_name(os.path.basename(p))
        if n is not None:
            ids.append(n)
    return f"{(max(ids) + 1 if ids else 1):04d}"


def read_front_matter(path):
    meta = {}
    with open(path, "r", encoding="utf-8") as f:
        s = f.read()

    # YAML front matter support (if present)
    if s.startswith("---"):
        parts = s.split("\n---", 1)
        if len(parts) > 1:
            fm = parts[0].lstrip("-\n")
            for line in fm.splitlines():
                if ":" in line:
                    k, v = line.split(":", 1)
                    meta[k.strip().lower()] = v.strip().strip('"').strip("'")

    # Markdown ADR metadata support (current ADR format)
    # Example: - **Tags:** safety, approvals
    md_meta = re.findall(r"^\s*-\s*\*\*([^*]+?)\s*:?\*\*\s*:?[ \t]*(.+?)\s*$", s, flags=re.M)
    for k, v in md_meta:
        meta[k.strip().lower()] = v.strip().strip('"').strip("'")

    # fallback: first markdown H1 as title
    if "title" not in meta:
        m = re.search(r"^#\s+(.+)$", s, flags=re.M)
        if m:
            meta["title"] = m.group(1).strip()
    return meta


def cmd_new(args):
    tid = next_id()
    slug = slugify(args.title)
    fname = os.path.join(ADR_DIR, f"ADR-{tid}-{slug}.md")
    tmpl = {
        "full": "_template-full.md",
        "lite": "_template-lite.md",
        "amend": "_template-amend.md",
    }[args.type]
    src = os.path.join(ADR_DIR, tmpl)
    if not os.path.exists(src):
        sys.exit(f"Template not found: {src}")
    os.makedirs(ADR_DIR, exist_ok=True)
    with open(src, "r", encoding="utf-8") as f:
        s = f.read()
    s = s.replace("<ADR-ID>", tid).replace("<DATE>", dt.date.today().isoformat())
    with open(fname, "w", encoding="utf-8", newline="\n") as f:
        f.write(s)
    print(f"Created {os.path.relpath(fname, ROOT)}")


def cmd_reindex(_args):
    rows = []
    for p in iter_adr_files():
        base = os.path.basename(p)
        n = adr_number_from_name(base)
        if n is None:
            continue
        meta = read_front_matter(p)
        title = meta.get("title", base)
        status = meta.get("status", "")
        date = meta.get("date", "")
        area = meta.get("area", "")
        tags = meta.get("tags", "")
        link = f"{base}"
        rows.append((n, f"[ADR-{n:04d}]({link})", status, date, tags, title, area))

    lines = [
        "# ADR Index",
        "",
        "<!-- generated by `python scripts/adr_tools.py reindex`; do not hand-edit -->",
        "",
        "| ADR | Status | Date | Tags | Title | Area |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for _n, adr, status, date, tags, title, area in rows:
        lines.append(f"| {adr} | {status} | {date} | {tags} | {title} | {area} |")

    os.makedirs(ADR_DIR, exist_ok=True)
    with open(INDEX, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Updated {os.path.relpath(INDEX, ROOT)} with {len(rows)} ADRs")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="cmd", required=True)
    pnew = sub.add_parser("new")
    pnew.add_argument("title")
    pnew.add_argument("--type", choices=["full", "lite", "amend"], default="full")
    pnew.set_defaults(func=cmd_new)
    sub.add_parser("reindex").set_defaults(func=cmd_reindex)
    args = ap.parse_args()
    args.func(args)
